global:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure

## Argo Configs
configs:
    # -- Bcrypt hashed admin password
    ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
    ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "$2a$10$wHlRXcweq2wGXiMDbREtVucTOL3VAsAI8JnCZoKfEY.OKmVqIqZ1W"
    # -- Admin password modification time. Eg. `"2006-01-02T15:04:05Z"`
    # @default -- `""` (defaults to current time)
    argocdServerAdminPasswordMtime: ""
