apiVersion: v1
kind: Endpoints
metadata:
  name: rpi3
subsets:
  - addresses:
      - ip: 192.68.1.145
    ports:
      - port: 10250
---
apiVersion: v1
kind: Service
metadata:
  name: rpi3
spec:
  ports:
    - port: 10250
      targetPort: 10351
